# Generated by Django 4.2.7 on 2023-11-05 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DishCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='კერძების კატეგორიის სახელი')),
            ],
        ),
        migrations.CreateModel(
            name='DrinkCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='სასმელების კატეგორიის სახელი')),
            ],
        ),
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='სასმელის სახელი')),
                ('content', models.TextField(blank=True, max_length=100, verbose_name='აღწერა')),
                ('weight', models.IntegerField(blank=True, verbose_name='გრამირება')),
                ('price', models.IntegerField(blank=True, verbose_name='ფასი')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%y/%m/%d/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drinks', to='rike_menu.drinkcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='კერძის სახელი')),
                ('content', models.TextField(blank=True, max_length=100, verbose_name='აღწერა')),
                ('weight', models.IntegerField(blank=True, verbose_name='გრამირება')),
                ('price', models.IntegerField(blank=True, verbose_name='ფასი')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%y/%m/%d/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='rike_menu.dishcategory')),
            ],
        ),
    ]
