# Generated by Django 4.2.7 on 2023-11-05 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rike_menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='content_en',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='აღწერა'),
        ),
        migrations.AddField(
            model_name='dish',
            name='content_ka',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='აღწერა'),
        ),
        migrations.AddField(
            model_name='dish',
            name='title_en',
            field=models.CharField(max_length=50, null=True, verbose_name='კერძის სახელი'),
        ),
        migrations.AddField(
            model_name='dish',
            name='title_ka',
            field=models.CharField(max_length=50, null=True, verbose_name='კერძის სახელი'),
        ),
        migrations.AddField(
            model_name='dishcategory',
            name='title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='კერძების კატეგორიის სახელი'),
        ),
        migrations.AddField(
            model_name='dishcategory',
            name='title_ka',
            field=models.CharField(max_length=100, null=True, verbose_name='კერძების კატეგორიის სახელი'),
        ),
        migrations.AddField(
            model_name='drink',
            name='content_en',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='აღწერა'),
        ),
        migrations.AddField(
            model_name='drink',
            name='content_ka',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='აღწერა'),
        ),
        migrations.AddField(
            model_name='drink',
            name='title_en',
            field=models.CharField(max_length=50, null=True, verbose_name='სასმელის სახელი'),
        ),
        migrations.AddField(
            model_name='drink',
            name='title_ka',
            field=models.CharField(max_length=50, null=True, verbose_name='სასმელის სახელი'),
        ),
        migrations.AddField(
            model_name='drinkcategory',
            name='title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='სასმელების კატეგორიის სახელი'),
        ),
        migrations.AddField(
            model_name='drinkcategory',
            name='title_ka',
            field=models.CharField(max_length=100, null=True, verbose_name='სასმელების კატეგორიის სახელი'),
        ),
    ]
